// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 18 Dec 2019 20:58:41 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package nk provides Go bindings for nuklear.h — a small ANSI C gui library.
*/
package nk
